language: rust
rust:
- nightly
deploy:
  provider: heroku
  api_key:
    secure: R/9QXLxjRI3jD6OgXPBweG6KKbVsM5vHhcIx60wGjCy2LL1Ron5nEuDMmvXKkL7gzLhuVvCy3Upps3ZGdQcrtb5U8w6FhnYLZwAH6+6wf/dGJ6K8G3VqkujEbI8dFWvdqV+845Y31Z6yWeLl8MGNLupdnCG1fZiA7b6+KGBhJU6YX+ZNRkfDTgSddHCUM+Al4xD0uvhhLIgzHgddSDzQxn1+hhN3pqVAU9cGXYFbd6Rlfx2kH2vK+A02LZKAdPHITeE9L49Q3Uhkko+gI7+vDqoiHDvUwkmR2bpxmuK5ews+7tHzYmknHcJZN7HVKB9SlmDufP1n8hnwc167dJgpiFpN/UCzUh88L9ecLrPEOor3s8YlVAtkUFkju4bE9j1ky5Ii3UXXaXTU6hPTQmEKBQd5SLa/Fr8ie7NgRazfqagtbShQxqBWrOjeGLCramISP5Rvt5tjNqdG89A3hsSUS0eWVLp/FUml7LX0MbD5Lyagz6s3rwm+sEt+pefhzX9XGCl1qWrASyTGFrJsS7hdUKMA15cfcJcNqz2C/JxGPOBOq1hQjdHNCiiBx+wNZ5CcZRwehxHgjqJg/YChH1x1CGPkhx21SHRax73wUVImfVP06E6chAMuxre5tf1U6LcQfw7pei8cJfbw+liZBQduL3S2dZJ/X41fiup6Ni500L4=
