language: rust
rust:
- nightly
deploy:
  provider: heroku
  app: cwh-helloworld
  api_key:
    secure: OsHd9ORXE7SwISrmhYrKicY4qaaszkM6ZL/ThOCIOOT+rLt8CP+SBkECoLkA7LiK92oLgKU4BctNy89yGdUIZ//ZJ9G2b3KHwPsJk1CxaxvomlJPD8omgoCzweSPfcqNP10YgMovrujd6rVZqKMGAhcmIG5JU4ll2FAe/2OWtu2y3AArQ3AX3FlhUXdzWu04J/gVJ/cU49blalvQA21FITi1F5txsLXKkPKM3WAtw4uznuaDX9ZctRMFgXFf5p6++/mDoPFmcyfEK/pT1puH1ucBdKG9cGsuAs5t/d+BzhJCaxRlVbWW6mPYVTPr8EZWcVK2AppkifhYgFgf2GVN65sGjxRCv1FVT+nzxtu5/PM8PzoAQo078B0gkyaIixJ2Vf74JVq8nigTyd5+FIH6XNm1vhPVhNQWSutOU2ERKyBv1CtN/XJPAY6Fm2GFx6XENOZbl2VsATtmBGVo/FAA8+BxG3n7R7Hi5s6YkJIXZ6vonZju9NUDfgOz3DIQergCrKA6+erhLnXlwbMnOOgeZJjbPkg/0OjKbenl9pKZjDXCBIELFWRrYNmz0CXH6NcUPi51RyF+OugDGtL2zZAImmjhdwe640HgkhSLOvp5A/IyVckzwMKw+hxMLr4Fq9wpOv29GSwHJGx+nSgdRVqYMTo5U8bcLER9PxuyTbMsU5E=
