language: rust
rust:
- nightly
deploy:
  provider: heroku
  app: cwh-helloworld
  api_key:
    secure: ibf5cWnPL8Y/aHx5Q79ChGt9Jk6sqRjm+ax0pS/1y6Vm5JstIKMnrclNNFbd36l5Bsmq0JO0Tavm0WOWpsSR9HZY4Xn/l7eOSprAwc3n1Z5dqlfZnKB+qwYlE1IbMaE3yErvvqcXkYaZE94yrbRw6L8izll04MQRSAx1yavUKWCNl56qIiAezHKSz0AIfGKIa6hMqLdKooR26dJeP/ZXc0PZtnW296rrz94AD8g1dqF9buBpw1kkoSZ2vgT0yx41n28X2NB/hUTVBg48x+VwUw4DNXGjMQCcf44NOJcFlqua+bEjKFKmUSznHYMbbUE5kyo9bmKOmo2ekf8qbsBmka5GCXBzQH/LTmPdknKn4ayUeTR4OqOGwCzjUdjulsUyryKmPsB8AWagTEOTWgYlfi6aXafGJebKYYTkATL0KBDwA14uMCYWCBPuB+sZHRDF3XpVYkdNlD8VEWp8qqDKNnjbCcjDMER21HwzK301jxU4EH758hCb/aSRhu+MivichwJmhS5UyHlgrAdH48Qh7AppYzmJBXTpz+sTfDZcY1YB1jJdHOvA4qj7xjMMhaExROYOhLnZYh5/EqHi2ePOiqkLQ5xltdESAMQMvHltxn9UkVCMkgpKYlwfuZ2f7DZJvbiembgPjqkWZF3Mekxe8dELlsfRBdm+sqvPQt7KkS4=
