language: rust
rust:
- nightly
deploy:
  provider: heroku
  app: cwh-helloworld
  api_key:
    secure: NCPquvcX2R3lPCoo35qONn0lLq5hZjUwS5X0rZaz4JZO9Gr0DohDFQq+r3mNvxtrbxNvrKj4Q4CJ+/xC/KuGvle/zYEsmkn+I614JlY7E6OprD5tYYZIq0GTGn/HsVH+RuDTCeh6yWYFao2XeczLSlIigC9t3R6OXerWCvz0pC67sfwqWWeMbV9aoHsP0NDAdXLF1yfKPk/geo4LavuMICcuzpL9H2KBZjgxEyOdjd5cjmsJn3RfXlwgFDD3FmMCrsmYGc2UijWVhm1T6Ej99Z/ectf+VB3AB5jo/Jzt9e4ysTzUTIwWY/Ih9JrkC5DFftekKtEI2SuJID0V9nOkRVADhD4GihU/MvEnNUxVwEc7NkWVBAOI0Ryltz/DDKvTXhl6aVsclU8pq5FGLXrHuaWjTBPOo0pkr9YrwvKsOe+P6gFLyWU7rhFBcrRGBm+M+jHm0RcD9gUV2rM/Ah6qJ9JLFLVw1rnF3mwRbyovi2e1sG2gZ0ryDR549EUn3DnHApkU20JVgKPMyQrNQ1M69RDnXNQpWqtvTquYHwwEZGnjMiPDH74evHG9prXgDNhXMpoSmGq7iBXsKqBCzbXcpt10EwrGD26OZG8iuDASb1Yfb8QJXIcoEH7bK8DkybmXKVFrj7XNve0rtNcW045gfxgrTwEDjwirOKCGw/Z9XXo=
